spring:
  application:
    name: learning
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/langchain_db}
      uuid-representation: standard
server:
  port: 8899

logging:
  level:
    org.springframework.security: DEBUG #Only for debug purpose

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o-mini
      log-request: true
      log-response: true
    # Add this block for the embedding model
    embedding-model:
      api-key: ${OPENAI_API_KEY}
      model-name: text-embedding-3-small

qdrant:
  host: localhost
  grpc-port: 6334
